### ISSUE TITLE
"npm run gen" required for solution to build / run

### ISSUE THREAD

**Issue by mormond** [Azure-Samples/js-e2e-graphql-cosmosdb-static-web-app#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow Getting Started -> Quickstart in readme to step 8

### Any log messages given by the failure
>

graphql/data/cosmos/GameDataSource.ts(3,27): error TS2307: Cannot find module '../../generated' or its corresponding type declarations.
graphql/data/inMemory/GameDataSource.ts(3,27): error TS2307: Cannot find module '../../generated' or its corresponding type declarations.
graphql/data/types.ts(1,27): error TS2307: Cannot find module '../generated' or its corresponding type declarations.
graphql/resolvers.ts(3,38): error TS2307: Cannot find module './generated' or its corresponding type declarations.

### Expected/desired behavior
> Solution should build / run.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Manually running "npm run gen" in the /api folder resolves the issue.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by diberry** [comment]
@mormond Thanks for reporting. I hit this recently too. It does seem like you have to run it manually the first time. I'll note that in the readme and related content. 

@aaronpowell have you seen this before where you have to run `graphql codegen` manually the first time?

**Comment by aaronpowell** [comment]
I've just tried to replicate on Windows and WSL, both worked as expected (didn't have to generate the file). I'm using Node 16 and here's the steps:

- Clone repo
- cd `js-e2e-graphql-cosmosdb-static-web-app\api`
- `npm i`
- `npm run build`

Can you share the repo steps, plus OS and Node versions?

**Comment by diberry** [comment]
@aaronpowell  I think I was on a mac and node 14. If I hit it again, I'll post back here.
